package mytour.user.entity;
// Generated Jun 21, 2016 11:07:44 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "mydb")
public class Comment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idComment;
	private int idUser;
	private int idTour;
	private String noiDung;

	public Comment() {
	}

	public Comment(int idUser, int idTour, String noiDung) {
		this.idUser = idUser;
		this.idTour = idTour;
		this.noiDung = noiDung;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_comment", unique = true, nullable = false)
	public Integer getIdComment() {
		return this.idComment;
	}

	public void setIdComment(Integer idComment) {
		this.idComment = idComment;
	}

	@Column(name = "ID_user", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "ID_tour", nullable = false)
	public int getIdTour() {
		return this.idTour;
	}

	public void setIdTour(int idTour) {
		this.idTour = idTour;
	}

	@Column(name = "noi_dung", nullable = false, length = 65535)
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

}
