package mytour.user.entity;
// Generated Jun 21, 2016 11:07:44 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HoaDon generated by hbm2java
 */
@Entity
@Table(name = "hoa_don", catalog = "mydb")
public class HoaDon implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idHoaDon;
	private int idChiTietHoaDon;
	private Date ngayThanhToan;
	private double tongGia;
	private String trangThai;

	public HoaDon() {
	}

	public HoaDon(int idChiTietHoaDon, Date ngayThanhToan, double tongGia, String trangThai) {
		this.idChiTietHoaDon = idChiTietHoaDon;
		this.ngayThanhToan = ngayThanhToan;
		this.tongGia = tongGia;
		this.trangThai = trangThai;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_hoa_don", unique = true, nullable = false)
	public Integer getIdHoaDon() {
		return this.idHoaDon;
	}

	public void setIdHoaDon(Integer idHoaDon) {
		this.idHoaDon = idHoaDon;
	}

	@Column(name = "id_chi_tiet_hoa_don", nullable = false)
	public int getIdChiTietHoaDon() {
		return this.idChiTietHoaDon;
	}

	public void setIdChiTietHoaDon(int idChiTietHoaDon) {
		this.idChiTietHoaDon = idChiTietHoaDon;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngay_thanh_toan", nullable = false, length = 19)
	public Date getNgayThanhToan() {
		return this.ngayThanhToan;
	}

	public void setNgayThanhToan(Date ngayThanhToan) {
		this.ngayThanhToan = ngayThanhToan;
	}

	@Column(name = "tong_gia", nullable = false, precision = 22, scale = 0)
	public double getTongGia() {
		return this.tongGia;
	}

	public void setTongGia(double tongGia) {
		this.tongGia = tongGia;
	}

	@Column(name = "trang_thai", nullable = false, length = 50)
	public String getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(String trangThai) {
		this.trangThai = trangThai;
	}

}
