package mytour.user.entity;
// Generated Jun 21, 2016 11:07:44 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Place generated by hbm2java
 */
@Entity
@Table(name = "place", catalog = "mydb")
public class Place implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idPlace;
	private int idDanhMuc;
	private String namePlace;
	private String imgLink;
	private TinTuc tinTuc;

	public Place() {
	}

	public Place(int idDanhMuc, String namePlace, String imgLink) {
		this.idDanhMuc = idDanhMuc;
		this.namePlace = namePlace;
		this.imgLink = imgLink;
	}

	public Place(int idDanhMuc, String namePlace, String imgLink, TinTuc tinTuc) {
		this.idDanhMuc = idDanhMuc;
		this.namePlace = namePlace;
		this.imgLink = imgLink;
		this.tinTuc = tinTuc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_place", unique = true, nullable = false)
	public Integer getIdPlace() {
		return this.idPlace;
	}

	public void setIdPlace(Integer idPlace) {
		this.idPlace = idPlace;
	}

	@Column(name = "id_danh_muc", nullable = false)
	public int getIdDanhMuc() {
		return this.idDanhMuc;
	}

	public void setIdDanhMuc(int idDanhMuc) {
		this.idDanhMuc = idDanhMuc;
	}

	@Column(name = "name_place", nullable = false, length = 300)
	public String getNamePlace() {
		return this.namePlace;
	}

	public void setNamePlace(String namePlace) {
		this.namePlace = namePlace;
	}

	@Column(name = "img_link", nullable = false, length = 300)
	public String getImgLink() {
		return this.imgLink;
	}

	public void setImgLink(String imgLink) {
		this.imgLink = imgLink;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "place")
	public TinTuc getTinTuc() {
		return this.tinTuc;
	}

	public void setTinTuc(TinTuc tinTuc) {
		this.tinTuc = tinTuc;
	}

}
