package mytour.user.entity;
// Generated Jun 21, 2016 11:07:44 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TinTuc generated by hbm2java
 */
@Entity
@Table(name = "tin_tuc", catalog = "mydb")
public class TinTuc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTin;
	private Place place;
	private String tenTin;
	private String tieuDe;
	private String noiDung;
	private int imgLink;

	public TinTuc() {
	}

	public TinTuc(Place place, String tenTin, String noiDung, int imgLink) {
		this.place = place;
		this.tenTin = tenTin;
		this.noiDung = noiDung;
		this.imgLink = imgLink;
	}

	public TinTuc(Place place, String tenTin, String tieuDe, String noiDung, int imgLink) {
		this.place = place;
		this.tenTin = tenTin;
		this.tieuDe = tieuDe;
		this.noiDung = noiDung;
		this.imgLink = imgLink;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "place"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id_tin", unique = true, nullable = false)
	public Integer getIdTin() {
		return this.idTin;
	}

	public void setIdTin(Integer idTin) {
		this.idTin = idTin;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Place getPlace() {
		return this.place;
	}

	public void setPlace(Place place) {
		this.place = place;
	}

	@Column(name = "ten_tin", nullable = false, length = 100)
	public String getTenTin() {
		return this.tenTin;
	}

	public void setTenTin(String tenTin) {
		this.tenTin = tenTin;
	}

	@Column(name = "tieu_de", length = 65535)
	public String getTieuDe() {
		return this.tieuDe;
	}

	public void setTieuDe(String tieuDe) {
		this.tieuDe = tieuDe;
	}

	@Column(name = "noi_dung", nullable = false, length = 65535)
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

	@Column(name = "img_link", nullable = false)
	public int getImgLink() {
		return this.imgLink;
	}

	public void setImgLink(int imgLink) {
		this.imgLink = imgLink;
	}

}
