package mytour.user.entity;
// Generated Jun 21, 2016 11:07:44 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tour generated by hbm2java
 */
@Entity
@Table(name = "tour", catalog = "mydb")
public class Tour implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTour;
	private String tenTour;
	private int idPlace;
	private String thoiGian;
	private int gia;
	private String noiDung;
	private String checkIn;
	private String checkOut;
	private String phuongTien;
	private String imgLink;

	public Tour() {
	}

	public Tour(String tenTour, int idPlace, String thoiGian, int gia, String noiDung, String checkIn, String checkOut,
			String phuongTien, String imgLink) {
		this.tenTour = tenTour;
		this.idPlace = idPlace;
		this.thoiGian = thoiGian;
		this.gia = gia;
		this.noiDung = noiDung;
		this.checkIn = checkIn;
		this.checkOut = checkOut;
		this.phuongTien = phuongTien;
		this.imgLink = imgLink;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tour", unique = true, nullable = false)
	public Integer getIdTour() {
		return this.idTour;
	}

	public void setIdTour(Integer idTour) {
		this.idTour = idTour;
	}

	@Column(name = "ten_tour", nullable = false, length = 300)
	public String getTenTour() {
		return this.tenTour;
	}

	public void setTenTour(String tenTour) {
		this.tenTour = tenTour;
	}

	@Column(name = "id_place", nullable = false)
	public int getIdPlace() {
		return this.idPlace;
	}

	public void setIdPlace(int idPlace) {
		this.idPlace = idPlace;
	}

	@Column(name = "thoi_gian", nullable = false, length = 100)
	public String getThoiGian() {
		return this.thoiGian;
	}

	public void setThoiGian(String thoiGian) {
		this.thoiGian = thoiGian;
	}

	@Column(name = "gia", nullable = false)
	public int getGia() {
		return this.gia;
	}

	public void setGia(int gia) {
		this.gia = gia;
	}

	@Column(name = "noi_dung", nullable = false, length = 16383)
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

	@Column(name = "check_in", nullable = false, length = 300)
	public String getCheckIn() {
		return this.checkIn;
	}

	public void setCheckIn(String checkIn) {
		this.checkIn = checkIn;
	}

	@Column(name = "check_out", nullable = false, length = 300)
	public String getCheckOut() {
		return this.checkOut;
	}

	public void setCheckOut(String checkOut) {
		this.checkOut = checkOut;
	}

	@Column(name = "phuong_tien", nullable = false, length = 100)
	public String getPhuongTien() {
		return this.phuongTien;
	}

	public void setPhuongTien(String phuongTien) {
		this.phuongTien = phuongTien;
	}

	@Column(name = "img_link", nullable = false, length = 300)
	public String getImgLink() {
		return this.imgLink;
	}

	public void setImgLink(String imgLink) {
		this.imgLink = imgLink;
	}

}
